[build]
  command = "npm run build"
  publish = "public/html/skillgro"

[[redirects]]
  from = "/"
  to = "/pages/index.html"
  status = 200

[[redirects]]
  from = "/:page"
  to = "/pages/:page.html"
  status = 200
