[build]
  command = "npm run build"
  publish = "build"        # Folder with static files
  functions = "netlify/functions"  # Folder with Node.js serverless functions

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
